//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShufflerFM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShufflerFM.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAboutText {
            get {
                return ResourceManager.GetString("AppBarAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shuffler.fm.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to featured blogs.
        /// </summary>
        public static string HeaderBlogs {
            get {
                return ResourceManager.GetString("HeaderBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genres.
        /// </summary>
        public static string HeaderGenres {
            get {
                return ResourceManager.GetString("HeaderGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trending.
        /// </summary>
        public static string HeaderPopular {
            get {
                return ResourceManager.GetString("HeaderPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and similar artists in.
        /// </summary>
        public static string TextAndSimilar {
            get {
                return ResourceManager.GetString("TextAndSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blogs.
        /// </summary>
        public static string TextBlogs {
            get {
                return ResourceManager.GetString("TextBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured on.
        /// </summary>
        public static string TextFeaturedOn {
            get {
                return ResourceManager.GetString("TextFeaturedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to.
        /// </summary>
        public static string TextListenTo {
            get {
                return ResourceManager.GetString("TextListenTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string TextLoading {
            get {
                return ResourceManager.GetString("TextLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string TextMore {
            get {
                return ResourceManager.GetString("TextMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more on.
        /// </summary>
        public static string TextReadMoreOn {
            get {
                return ResourceManager.GetString("TextReadMoreOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to this track on.
        /// </summary>
        public static string TextShufflerListenOnShuffler {
            get {
                return ResourceManager.GetString("TextShufflerListenOnShuffler", resourceCulture);
            }
        }
    }
}
